# Generated by Django 4.2.3 on 2023-08-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
