# Generated by Django 4.2.3 on 2023-08-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_newuser_email_confirmed_newuser_is_banned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailconfirmationtoken',
            old_name='customer',
            new_name='user',
        ),
    ]
