# Generated by Django 4.2.3 on 2023-08-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_customer_emailconfirmationtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='time_deleted',
            field=models.DateTimeField(null=True),
        ),
    ]
