# Generated by Django 4.2.3 on 2023-08-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_newuser_time_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(error_messages='Такой почтовый адрес уже занят', max_length=254, unique=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(error_messages='Такое имя уже занято', max_length=150, unique=True),
        ),
    ]
