# Generated by Django 4.2.3 on 2023-08-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_newuser_user_name'),
        ('accounts', '0005_newuser_time_deleted'),
    ]

    operations = [
    ]
