# Generated by Django 4.2.3 on 2023-08-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_newuser_email_alter_newuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='time_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
