# Generated by Django 4.2.3 on 2023-08-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20230815_1756'),
        ('accounts', '0008_alter_newuser_time_deleted'),
    ]

    operations = [
    ]
