# Generated by Django 4.2.3 on 2023-09-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_newuser_time_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватарка'),
        ),
    ]
