# Generated by Django 4.2.3 on 2023-09-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_newuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(db_index=True, error_messages={'unique': 'Указаное имя уже занято.'}, max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
