# Generated by Django 4.2.3 on 2023-10-12 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_newuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='emailconfirmationtoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'Указаный почтовый адрес уже занято.'}, max_length=254, unique=True, verbose_name='Почтовый адрес'),
        ),
    ]
