# Generated by Django 4.2.3 on 2023-08-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_theme_is_parent_theme_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theme',
            new_name='ThemeTag',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tag',
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(related_name='theme_tags', to='forum.themetag', verbose_name='Тег'),
        ),
    ]
