# Generated by Django 4.2.3 on 2023-08-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_theme_themetag_remove_question_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(related_name='theme_tags', to='forum.themetag', verbose_name='Тег'),
        ),
    ]
