# Generated by Django 4.2.3 on 2023-08-18 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0008_rename_tag_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='themetag',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='themetag',
            name='is_relevant',
            field=models.BooleanField(default=True, verbose_name='Релеватный тег'),
        ),
        migrations.AddField(
            model_name='themetag',
            name='is_user_tag',
            field=models.BooleanField(default=False, verbose_name='Авторский тег'),
        ),
        migrations.AddField(
            model_name='themetag',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='Автор, если есть'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='themetag',
            name='tag',
            field=models.CharField(max_length=255, unique=True, verbose_name='Тег'),
        ),
    ]
