# Generated by Django 4.2.3 on 2023-08-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_themetag_creation_date_themetag_is_relevant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='questions', to='forum.themetag', verbose_name='Тег'),
        ),
    ]
