# Generated by Django 4.2.3 on 2023-08-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_questionimages_questionanswerimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswerimages',
            name='image',
            field=models.ImageField(upload_to='answer_img/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='questionimages',
            name='image',
            field=models.ImageField(upload_to='question_img/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
