# Generated by Django 4.2.3 on 2023-08-25 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_alter_questionanswerimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswerimages',
            name='question_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_images', to='forum.questionanswer'),
        ),
    ]
