# Generated by Django 4.2.3 on 2023-08-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_questionanswerimages_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswerimages',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативный текст'),
        ),
        migrations.AlterField(
            model_name='questionanswerimages',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='questionimages',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Альтернативный текст'),
        ),
        migrations.AlterField(
            model_name='questionimages',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
