# Generated by Django 4.2.3 on 2023-08-25 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_alter_questionanswerimages_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerimages',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forum.question'),
        ),
        migrations.AddField(
            model_name='questionimages',
            name='question_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forum.questionanswer'),
        ),
    ]
