# Generated by Django 4.2.3 on 2023-08-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_questionanswerimages_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswerimages',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionimages',
            name='question_answer',
        ),
    ]
