# Generated by Django 4.2.3 on 2023-08-25 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_remove_questionanswerimages_question_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswerimages',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answer_images', to='forum.questionanswer', verbose_name='Ответ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionimages',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_images', to='forum.question', verbose_name='Вопрос'),
            preserve_default=False,
        ),
    ]
