# Generated by Django 4.2.3 on 2023-08-25 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_alter_questionanswerimages_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercomment',
            name='question_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_comments', to='forum.questionanswer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='comment',
            field=models.TextField(max_length=320, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.TextField(verbose_name='Текс ответа'),
        ),
    ]
