# Generated by Django 4.2.3 on 2023-08-26 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_answercomment_question_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='forum.answercomment'),
        ),
    ]
