# Generated by Django 4.2.3 on 2023-08-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_answercomment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answercomment',
            name='parent_comment',
        ),
    ]
