# Generated by Django 4.2.3 on 2023-08-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_alter_questionanswerrating_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswerrating',
            name='dislike_amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswerrating',
            name='like_amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionrating',
            name='dislike_amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionrating',
            name='like_amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
