# Generated by Django 4.2.3 on 2023-08-26 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_alter_questionanswerrating_dislike_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswerrating',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='forum.questionanswer'),
        ),
        migrations.AlterField(
            model_name='questionrating',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='forum.question'),
        ),
    ]
