# Generated by Django 4.2.3 on 2023-08-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_alter_questionanswerrating_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswerrating',
            old_name='question',
            new_name='answer',
        ),
    ]
