# Generated by Django 4.2.3 on 2023-08-27 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0026_rename_question_questionanswerrating_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswerrating',
            old_name='answer',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='questionrating',
            old_name='question',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='questionanswerrating',
            name='users_rated',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AddField(
            model_name='questionrating',
            name='users_rated',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
