# Generated by Django 4.2.3 on 2023-08-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0027_rename_answer_questionanswerrating_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswerrating',
            old_name='parent',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='questionrating',
            old_name='parent',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='questionanswerrating',
            name='users_rated',
        ),
        migrations.RemoveField(
            model_name='questionrating',
            name='users_rated',
        ),
    ]
