# Generated by Django 4.2.3 on 2023-08-27 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0028_rename_parent_questionanswerrating_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerrating',
            name='disliked_by_users',
            field=models.ManyToManyField(blank=True, related_name='disliked_answer_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionanswerrating',
            name='liked_by_users',
            field=models.ManyToManyField(blank=True, related_name='liked_answer_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionrating',
            name='disliked_by_users',
            field=models.ManyToManyField(blank=True, related_name='disliked_question_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionrating',
            name='liked_by_users',
            field=models.ManyToManyField(blank=True, related_name='liked_question_ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
