# Generated by Django 4.2.3 on 2023-08-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0029_questionanswerrating_disliked_by_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswerrating',
            old_name='disliked_by_users',
            new_name='user_disliked',
        ),
        migrations.RenameField(
            model_name='questionanswerrating',
            old_name='liked_by_users',
            new_name='user_liked',
        ),
        migrations.RenameField(
            model_name='questionrating',
            old_name='disliked_by_users',
            new_name='user_disliked',
        ),
        migrations.RenameField(
            model_name='questionrating',
            old_name='liked_by_users',
            new_name='user_liked',
        ),
    ]
