# Generated by Django 4.2.3 on 2023-08-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0030_rename_disliked_by_users_questionanswerrating_user_disliked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswerrating',
            old_name='user_disliked',
            new_name='users_disliked',
        ),
        migrations.RenameField(
            model_name='questionanswerrating',
            old_name='user_liked',
            new_name='users_liked',
        ),
        migrations.RenameField(
            model_name='questionrating',
            old_name='user_disliked',
            new_name='users_disliked',
        ),
        migrations.RenameField(
            model_name='questionrating',
            old_name='user_liked',
            new_name='users_liked',
        ),
    ]
