# Generated by Django 4.2.3 on 2023-08-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0031_rename_user_disliked_questionanswerrating_users_disliked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themetag',
            old_name='tag',
            new_name='tag_name',
        ),
    ]
