# Generated by Django 4.2.3 on 2023-08-31 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0032_rename_tag_themetag_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercomment',
            name='question_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_comments', to='forum.questionanswer', verbose_name='Ответ на вопрос (ID)'),
        ),
    ]
