# Generated by Django 4.2.3 on 2023-09-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0033_alter_answercomment_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_solved',
            field=models.BooleanField(default=False, verbose_name='Вопрос решен'),
        ),
    ]
