# Generated by Django 4.2.3 on 2023-09-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0034_question_is_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercomment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
