# Generated by Django 4.2.3 on 2023-09-26 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0036_rename_updated_answercomment_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.questionanswer'),
        ),
    ]
