# Generated by Django 4.2.3 on 2023-09-26 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0037_questionanswer_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='parent',
        ),
        migrations.AddField(
            model_name='answercomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.answercomment'),
        ),
    ]
