# Generated by Django 4.2.3 on 2023-10-11 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0039_questionanswerrating_users_complained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrating',
            name='users_complained',
            field=models.ManyToManyField(blank=True, related_name='comment_rating_complained', to=settings.AUTH_USER_MODEL, verbose_name='Пожаловавшиеся пользователи'),
        ),
        migrations.AlterField(
            model_name='questionanswerrating',
            name='users_complained',
            field=models.ManyToManyField(blank=True, related_name='answer_rating_complained', to=settings.AUTH_USER_MODEL, verbose_name='Пожаловавшиеся пользователи'),
        ),
        migrations.AlterField(
            model_name='questionrating',
            name='users_complained',
            field=models.ManyToManyField(blank=True, related_name='question_rating_complained', to=settings.AUTH_USER_MODEL, verbose_name='Пожаловавшиеся пользователи'),
        ),
    ]
