# Generated by Django 4.2.3 on 2023-10-11 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0040_alter_commentrating_users_complained_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentrating',
            options={'verbose_name': 'Рейтинг комментария', 'verbose_name_plural': 'Рейтинги комментариев'},
        ),
        migrations.AlterField(
            model_name='commentrating',
            name='users_complained',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_rating_complained', to=settings.AUTH_USER_MODEL, verbose_name='Пожаловавшиеся пользователи'),
        ),
    ]
