# Generated by Django 4.2.3 on 2023-10-11 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0041_alter_commentrating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrating',
            name='users_complained',
            field=models.ManyToManyField(blank=True, related_name='comment_rating_complained', to=settings.AUTH_USER_MODEL, verbose_name='Пожаловавшиеся пользователи'),
        ),
    ]
