# Generated by Django 4.2.3 on 2023-10-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0042_alter_commentrating_users_complained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrating',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='forum.answercomment'),
        ),
    ]
