# Generated by Django 4.2.3 on 2023-10-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0043_alter_commentrating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themetag',
            name='is_relevant',
            field=models.BooleanField(default=True, verbose_name='Релевантный тег'),
        ),
    ]
