name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.11 ]
    env:
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./backend
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        working-directory: ./backend
        run:
          flake8
      - name: Test project
        working-directory: ./backend
        run: python manage.py test