name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Set up PostgreSQL for testing
        run: |
          docker run --name test-postgres -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} -d -p 5432:5432 postgres:14.1-alpine
          sleep 5
      - name: Lint with flake8
        run: flake8 backend
      - name: Test project
        run: python backend/manage.py test
      - name: Clean up PostgreSQL container
        run: docker rm -f test-postgres

