name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.11 ]

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - name: Setup database
        run: psql -h postgres -U postgres_user -c 'CREATE DATABASE "postgres_db";'
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./backend
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        working-directory: ./backend
        run:
          flake8
      - name: Test project
        working-directory: ./backend
        run: python manage.py test
